joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  
joint7_controller:
  type: effort_controllers/JointPositionController
  joint: joint_7
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint8_controller:
  type: effort_controllers/JointPositionController
  joint: joint_8
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint9_controller:
  type: effort_controllers/JointPositionController
  joint: joint_9
  pid: {p: 100.0, i: 0.01, d: 10.0}